name: Code Check and Doc Gen

on:  [pull_request]

permissions:
  contents: read
  actions: read

jobs:
  # Ensure the project can build first
  build:
    permissions:
      contents: read
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Get dependencies
        run: |
          go mod tidy
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference after 'go mod tidy'. Run 'go mod tidy' command and commit."; exit 1)
      - name: Build
        run: |
          make install
  fmt:
    permissions:
      contents: read
    name: go fmt
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: |
          if [ "$(go fmt ./... | wc -l)" -gt 0 ]; then
            echo "::error::'go fmt' found required formatting changes. Run 'make fmt' on your branch."
            exit 1;
          fi

  gosec:
    permissions:
      contents: read
    name: Run Gosec 
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
      - run: |
          echo "Checking Security"
          make sec

  vet:
    permissions:
      contents: read
    name: go vet
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go vet ./...

  lint:
    permissions:
      contents: read
    name: golangcli-lint
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        env:
          ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
        with:
          version: latest
          args: "--config .golintci.yml"
          only-new-issues: true

  # generate:
  #   name: go generate
  #   needs: [build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
  #     - uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4.3.0
  #       with:
  #         go-version-file: 'go.mod'
  #         cache: true
  #     - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
  #       with:
  #         terraform_version: 1.9.4
  #     - run: |
  #         go generate ./...
  #         git add -N .
  #         git diff --exit-code || \
  #           (echo; echo "Unexpected difference after code generation. Run 'make generate' command and commit."; exit 1)
